import Head from "next/head";
import Image from "next/image";
import Announcement from "../components/Announcement";
import BigHeader from "../components/BigHeader";
import Brand from "../components/Brand";
import BrandSlider from "../components/BrandSlider";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hiro from "../components/Hiro";
import ProductsBox from "../components/ProductsBox";
import Randevu from "../components/Randevu";
import Services from "../components/Services";
import SingleProduct from "../components/SingleProduct";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <BigHeader />
      <div className="w-full max-w-[1500px] mx-auto">
        <Head>
          <title>ikinci el esiya alim satim an iyi fiyata </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Announcement /> */}
        <Header />

        <Hiro />
        <Randevu />
        <Services />
        <BrandSlider
          value={[
            { img: "/samsung.jpg" },
            { img: "/siemens.jpg" },
            { img: "/vestel.jpg" },
            { img: "/lg.jpg" },
            { img: "/profilo.jpg" },
            { img: "/altus.jpg" },
            { img: "/arcelik.jpg" },

            { img: "/beko.jpg" },
            { img: "/bosch.jpg" },
            { img: "/grunding.jpg" },
          ]}
        />
        <ProductsBox />
      </div>
      <Footer />
    </>
  );
}
